<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>حول</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- bootstrap css -->
   <link rel="stylesheet" href="css/bootstrap.min.css">
   <!-- style css -->
   <link rel="stylesheet" href="css/style.css">
   <!-- Responsive-->
   <link rel="stylesheet" href="css/responsive.css">
   <!-- fevicon -->
   <link rel="icon" href="images/fevicon.png" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
   <!-- Tweaks for older IEs-->
   <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
      media="screen">
   <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
      <!-- loader  -->
      <div class="loader_bg">
         <div class="loader"><img src="images/loading.gif" alt="#"/></div>
      </div>
      <!-- end loader -->
      <!-- header -->
      <header>
         <!-- header inner -->
         <div class="header">
            <div class="container-fluid">
               <div class="row">
                  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                     <div class="full">
                        <div class="center-desk">
                           <div class="logo">
                              <a href="Old_index1.php"><img src="images/logo.png" alt="#" /></a>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-xl-7 col-lg-7 col-md-9 col-sm-9">
                     <nav class="navigation navbar navbar-expand-md navbar-dark ">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarsExample04">
                           <ul class="navbar-nav mr-auto">
                              <li class="nav-item">
                                 <a class="nav-link" href="Old_index1.php">الرئسية</a>
                              </li>
                              <li class="nav-item active">
                                 <a class="nav-link" href="about.php">حول</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="register.php">تسجيل طالب</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="lecture.php">محاضرات</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="./Reports/Reports_.php">تقارير</a>
                              </li>
                              <li class="nav-item">
                                 <a class="nav-link" href="login.php"> تسجيل خروج</a>
                               </li>
                              
                           </ul>
                        </div>
                     </nav>
                  </div>
                  <div class="col-md-2">
                     <ul class="social_icon">
                        <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                     </ul>
                  </div>
               </div>
            </div>
         </div>
   </header>
   <!-- end header inner -->
   <!-- end header -->
   <div class="back_re">
      <div class="container">
         <div class="row">
            <div class="col-md-12">
               <div class="title">
                  <h2>حول </h2>
               </div>
            </div>
         </div>
      </div>
   </div>

   <!-- about -->
   <div class="">
      <div class="container">
         <div class="row d_flex">
            <div class="col-md-6">
               <div class="titlepage" dir="rtl" style="text-align: right;">
                  <h2 class="mb-2">حول المنظومة</h2>
                  <p>منظومة الحضور والغياب للطلاب تقوم هذه المنظومة بتطوير نظام اداري يسهل علي المحاضرين عملية متابعة
                     الحضور والغياب للطلاب,كما تهدف هذه المنظومة علي تطوير نظام يساعد الطلاب بتسجيل الحضور والغياب وذلك
                     عبر بصمة الأصبع .</p>

               </div>
            </div>
            <div class="col-md-6">
               <div class="about_img">
                  <figure><img src="images/about.png" alt="#" /></figure>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- end about -->

   <!-- what we do  -->
   <div class="mt-4 p-3">
      <div class="container">
         <div class="text-center" style="font-size: 50px; font-weight: bold;">خدمات المنظومة</div>
         <div class="row">
            <div class="d-flex justify-content-around mx-2">
               <div class="col-md-3 col-sm-6">
                  <div class="we_box">
                     <i><img src="images/percision.png" alt="#" /></i>
                     <h3>الدقـــة</h3>
                     <p>الدقة في رصد البيانات وبتبقى محفوظة في المنظومة مع سهولة الرجوع إليه </p>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6">
                  <div class="we_box">
                     <i><img src="images/speed.png" alt="#" /></i>
                     <h3>توفير الوقت</h3>
                     <p>يوفر على المحاضرين والطلاب الوقت وذلك عبر تسريع عملية تسجيل الحضور والغياب </p>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6">
                  <div class="we_box">
                     <i><img src="images/Stimulus.png" alt="#" /></i>
                     <h3>التحفيز</h3>
                     <p>دافع لالتزام الطالب لحضور المحاضرات </p>
                  </div>
               </div>
               <div class="col-md-3 col-sm-6">
                  <div class="we_box">
                     <i><img src="images/credibility.WEBP" alt="#" /></i>
                     <h3>المصداقية</h3>
                     <p>يمنع تسجلات الدخول الزائفة عن طريق بصمة الاصبع</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- end what we do  -->

   <!-- Javascript files-->
   <script src="js/jquery.min.js"></script>
   <script src="js/bootstrap.bundle.min.js"></script>
   <script src="js/jquery-3.0.0.min.js"></script>
   <!-- sidebar -->
   <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
   <script src="js/custom.js"></script>
</body>

</html>